{
    for (int i = 0; i < 10; i += 1);

    for (int i = 0; i < 10; i += 1) {}

    for (int i = 0; i < 10;);

    for (; i < 10;);

    for (; i < 10;) {}

    for (;; i += 10);

    for (;; i += 10) {}

    for (; i < 10;);

    for (; i < 10;) {}

    for (int i = 0;; i += 10);

    for (int i = 0;; i += 10) {}

    for (;;);

    for (;;){}

    for (;;) {
        test()
    }

    for (i = 10; i < 100; i += 1);

    for (i = 10; i < 100; i += 1, j += 2, test());

    for {
        test()
    }

    for test()
}
