{

    if (a > b) {}

    if (value) {}

    if (a > b)
        println();

    if (a)
        doB();
    else
        doC();

    if (a > b) {
        abcdf();
    } else if (b >= c) {
        gg();
    }

    if (a)
        b();
    else if (b)
        c();
    else
        d();

    if (abc)
        d()
    else e()

    var a = if (b > c) d else e

    var abcd = if (a > b)
        test()
        else
        test() + 20
}
